#!/bin/bash

set -e

curr_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

extern_bins=(
    "yarn:yarn --version"
    "node:node --version"
)

printf "ci starting... curr_dir: "${curr_dir}"\n"

for pair in "${extern_bins[@]}"; do
    key="${pair%%:*}"
    command_string="${pair#*:}"
    
    if command -v "$key" &> /dev/null; then
        version="$($command_string)"
        printf "Found %s, version: %s\n" "$key" "$version"
    else
        printf "%s is not installed, exiting the program\n" "$key"
        exit 1
    fi
done

cd ./internals/ci;
PROJECT_ROOT="$curr_dir" yarn --cwd ./internals/ci ci "$@"

exit 0;
